### ISSUE TITLE
Error: "message":"Handler does not support user"

### ISSUE THREAD

**Issue by j3mu5** [petergridge/openweathremaphistory#24]
When I try to configure the sensor under Integrations, I get an error message. In an earlier version, it was possible to customize the sensor after creating it.

![image](https://github.com/petergridge/openweathermaphistory/assets/50756558/9eb30424-4a98-4b1e-a208-dfd4e2b61df4)
![image](https://github.com/petergridge/openweathermaphistory/assets/50756558/2cfdad76-b54f-4ec7-a4c8-738e24aae25e)

**Comment by petergridge** [comment]
The recent update to HA introduced this issue, version 2.0.10 should fix it, I have just upgraded it to the main release.

Let me know how you go.
